print ("Welcome to Sommai Shop")
print ("-----------------------")
print ("Apple x", 3, 30,"THB - ",3*30,"THB")
print ("Banana x", 1, 10,"THB - ",1*10, "THB")
print ("Orange x",2,20,"THB - ",2*20,"THB")
print ("-----------------------")
print ("Total",3*30+1*10+2*20,"THB")
print ("Thank you : Sommai Shop")
